-- ThinkMark v2: Supabase Auth + per-user 4-character marks + RLS
create extension if not exists pgcrypto;
create table if not exists public.profiles(id uuid primary key references auth.users(id) on delete cascade,username varchar(24) not null unique,email text not null,created_at timestamptz not null default now());
create table if not exists public.notes(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,code varchar(4) not null,content text not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),constraint notes_user_code_unique unique(user_id,code),constraint notes_code_format check(code ~ '^[a-z0-9]{4}$'));
create index if not exists notes_user_created_idx on public.notes(user_id,created_at desc);create index if not exists notes_user_code_idx on public.notes(user_id,code);
alter table public.profiles enable row level security;alter table public.notes enable row level security;
drop policy if exists profiles_select_own on public.profiles;create policy profiles_select_own on public.profiles for select to authenticated using(auth.uid()=id);
drop policy if exists profiles_update_own on public.profiles;create policy profiles_update_own on public.profiles for update to authenticated using(auth.uid()=id) with check(auth.uid()=id);
drop policy if exists notes_select_own on public.notes;create policy notes_select_own on public.notes for select to authenticated using(auth.uid()=user_id);
drop policy if exists notes_insert_own on public.notes;create policy notes_insert_own on public.notes for insert to authenticated with check(auth.uid()=user_id);
drop policy if exists notes_update_own on public.notes;create policy notes_update_own on public.notes for update to authenticated using(auth.uid()=user_id) with check(auth.uid()=user_id);
drop policy if exists notes_delete_own on public.notes;create policy notes_delete_own on public.notes for delete to authenticated using(auth.uid()=user_id);
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ declare requested_username text;begin requested_username:=lower(trim(new.raw_user_meta_data->>'username'));if requested_username is null or requested_username !~ '^[a-z0-9_]{3,24}$' then raise exception 'Invalid username';end if;insert into public.profiles(id,username,email) values(new.id,requested_username,new.email);return new;end;$$;
drop trigger if exists on_auth_user_created on auth.users;create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
create or replace function public.is_username_available(requested_username text) returns boolean language sql security definer set search_path=public as $$ select not exists(select 1 from public.profiles where lower(username)=lower(trim(requested_username)));$$;revoke all on function public.is_username_available(text) from public;grant execute on function public.is_username_available(text) to anon,authenticated;
create or replace function public.get_email_for_username(requested_username text) returns text language sql security definer set search_path=public as $$ select email from public.profiles where lower(username)=lower(trim(requested_username)) limit 1;$$;revoke all on function public.get_email_for_username(text) from public;grant execute on function public.get_email_for_username(text) to anon,authenticated;
create or replace function public.sync_profile_email() returns trigger language plpgsql security definer set search_path=public as $$ begin update public.profiles set email=new.email where id=new.id;return new;end;$$;
drop trigger if exists on_auth_user_updated on auth.users;create trigger on_auth_user_updated after update of email on auth.users for each row execute procedure public.sync_profile_email();
